name: JSON to M3U Bot

on:
  schedule:
    - cron: "0 */6 * * *"   # har 6 ghante run hoga
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: ls -la

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python convert.py

      - name: Commit & Push
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add playlist.m3u
          git commit -m "Auto update M3U" || echo "No changes"
          git push
